In [4]:
# Required modules
import scipy as sp
import numpy as np
import pandas as pd
import matplotlib
import IPython
import sklearn
import graphviz
import mglearn
import sys

print("Python Version: {}".format(sys.version))
print("Pandas Version: {}".format(pd.__version__))
print("matplotlib Version: {}".format(matplotlib.__version__))
print("NumPy Version: {}".format(np.__version__))
print("SciPy Version: {}".format(sp.__version__))
print("IPython Version: {}".format(IPython.__version__))
print("Scikit-learn Version: {}".format(sklearn.__version__))
print("graphviz Version: {}".format(graphviz.__version__))
print("Mglearn Version: {}".format(mglearn.__version__))


Python Version: 3.5.3 (default, May 10 2017, 15:05:55) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
Pandas Version: 0.20.1
matplotlib Version: 2.0.2
NumPy Version: 1.12.1
SciPy Version: 0.19.0
IPython Version: 6.0.0
Scikit-learn Version: 0.18.1
graphviz Version: 0.7.1
Mglearn Version: 0.1.5


In [37]:
# Constant parameters given by the DySpan PU setup                              
DELAY_1 = 0.005 # tau1                                                          
DELAY_2 = 0.01  # tau2                                                          
TCONST = 0.002                                                                  
MEAN1 = 0.02    # lambda1                                                       
MEAN2 = 0.01    # lambda2                                                       
MEAN3 = 0.005   # lambda3 
N_CHAN = 4      # Number of channels
N_SCN = 10      # Number of scenarios

In [33]:
# save the recorded data in variables                                           
# interframe time per channel
# Scenario 0
if_time_ch1_scn_0 = sp.fromfile(open("interframe_time_ch_1_scn_0.dat"), dtype=sp.float32)                   
if_time_ch2_scn_0 = sp.fromfile(open("interframe_time_ch_2_scn_0.dat"), dtype=sp.float32)                   
if_time_ch3_scn_0 = sp.fromfile(open("interframe_time_ch_3_scn_0.dat"), dtype=sp.float32)                   
if_time_ch4_scn_0 = sp.fromfile(open("interframe_time_ch_4_scn_0.dat"), dtype=sp.float32)
# Scenario 1
if_time_ch1_scn_1 = sp.fromfile(open("interframe_time_ch_1_scn_1.dat"), dtype=sp.float32)                   
if_time_ch2_scn_1 = sp.fromfile(open("interframe_time_ch_2_scn_1.dat"), dtype=sp.float32)                   
if_time_ch3_scn_1 = sp.fromfile(open("interframe_time_ch_3_scn_1.dat"), dtype=sp.float32)                   
if_time_ch4_scn_1 = sp.fromfile(open("interframe_time_ch_4_scn_1.dat"), dtype=sp.float32)
# Scenario 2
if_time_ch1_scn_2 = sp.fromfile(open("interframe_time_ch_1_scn_2.dat"), dtype=sp.float32)                   
if_time_ch2_scn_2 = sp.fromfile(open("interframe_time_ch_2_scn_2.dat"), dtype=sp.float32)                   
if_time_ch3_scn_2 = sp.fromfile(open("interframe_time_ch_3_scn_2.dat"), dtype=sp.float32)                   
if_time_ch4_scn_2 = sp.fromfile(open("interframe_time_ch_4_scn_2.dat"), dtype=sp.float32)
# Scenario 3
if_time_ch1_scn_3 = sp.fromfile(open("interframe_time_ch_1_scn_3.dat"), dtype=sp.float32)                   
if_time_ch2_scn_3 = sp.fromfile(open("interframe_time_ch_2_scn_3.dat"), dtype=sp.float32)                   
if_time_ch3_scn_3 = sp.fromfile(open("interframe_time_ch_3_scn_3.dat"), dtype=sp.float32)                   
if_time_ch4_scn_3 = sp.fromfile(open("interframe_time_ch_4_scn_3.dat"), dtype=sp.float32)
# Scenario 4
if_time_ch1_scn_4 = sp.fromfile(open("interframe_time_ch_1_scn_4.dat"), dtype=sp.float32)                   
if_time_ch2_scn_4 = sp.fromfile(open("interframe_time_ch_2_scn_4.dat"), dtype=sp.float32)                   
if_time_ch3_scn_4 = sp.fromfile(open("interframe_time_ch_3_scn_4.dat"), dtype=sp.float32)                   
if_time_ch4_scn_4 = sp.fromfile(open("interframe_time_ch_4_scn_4.dat"), dtype=sp.float32)
# Scenario 5
if_time_ch1_scn_5 = sp.fromfile(open("interframe_time_ch_1_scn_5.dat"), dtype=sp.float32)                   
if_time_ch2_scn_5 = sp.fromfile(open("interframe_time_ch_2_scn_5.dat"), dtype=sp.float32)                   
if_time_ch3_scn_5 = sp.fromfile(open("interframe_time_ch_3_scn_5.dat"), dtype=sp.float32)                   
if_time_ch4_scn_5 = sp.fromfile(open("interframe_time_ch_4_scn_5.dat"), dtype=sp.float32)
# Scenario 6
if_time_ch1_scn_6 = sp.fromfile(open("interframe_time_ch_1_scn_6.dat"), dtype=sp.float32)                   
if_time_ch2_scn_6 = sp.fromfile(open("interframe_time_ch_2_scn_6.dat"), dtype=sp.float32)                   
if_time_ch3_scn_6 = sp.fromfile(open("interframe_time_ch_3_scn_6.dat"), dtype=sp.float32)                   
if_time_ch4_scn_6 = sp.fromfile(open("interframe_time_ch_4_scn_6.dat"), dtype=sp.float32)
# Scenario 7
if_time_ch1_scn_7 = sp.fromfile(open("interframe_time_ch_1_scn_7.dat"), dtype=sp.float32)                   
if_time_ch2_scn_7 = sp.fromfile(open("interframe_time_ch_2_scn_7.dat"), dtype=sp.float32)                   
if_time_ch3_scn_7 = sp.fromfile(open("interframe_time_ch_3_scn_7.dat"), dtype=sp.float32)                   
if_time_ch4_scn_7 = sp.fromfile(open("interframe_time_ch_4_scn_7.dat"), dtype=sp.float32)
# Scenario 8
if_time_ch1_scn_8 = sp.fromfile(open("interframe_time_ch_1_scn_8.dat"), dtype=sp.float32)                   
if_time_ch2_scn_8 = sp.fromfile(open("interframe_time_ch_2_scn_8.dat"), dtype=sp.float32)                   
if_time_ch3_scn_8 = sp.fromfile(open("interframe_time_ch_3_scn_8.dat"), dtype=sp.float32)                   
if_time_ch4_scn_8 = sp.fromfile(open("interframe_time_ch_4_scn_8.dat"), dtype=sp.float32)
# Scenario 9
if_time_ch1_scn_9 = sp.fromfile(open("interframe_time_ch_1_scn_9.dat"), dtype=sp.float32)                   
if_time_ch2_scn_9 = sp.fromfile(open("interframe_time_ch_2_scn_9.dat"), dtype=sp.float32)                   
if_time_ch3_scn_9 = sp.fromfile(open("interframe_time_ch_3_scn_9.dat"), dtype=sp.float32)                   
if_time_ch4_scn_9 = sp.fromfile(open("interframe_time_ch_4_scn_9.dat"), dtype=sp.float32)

In [28]:
# Or avoid doing that per hand and create a list with the following format:
# if_time_scn_[]_ch_[]
# [[scenario 0, channel 1], [scenario 0, channel 2], ..., [scenario 0, channel 4]],
# [[scenario 1, channel 1], [scenario 1, channel 2], ..., [scenario 1, channel 4]],
# .
# .
# .
# [[scenario 9, channel 1], [scenario 9, channel 2], ..., [scenario 9, channel 4]],

# BETTER TO START THINKING IN CHANNEL 0 TO 3

if_time_scn_ch = [[[channel] for channel in range(N_CHAN)] for scenario in range(N_SCN)]

for scenario in range(N_SCN):
    for channel in range(N_CHAN):
        if_time_scn_ch[scenario][channel] = sp.fromfile(open(
            "interframe_time_ch_{}_scn_{}.dat".format(channel+1, scenario)), dtype=sp.float32)      
        

In [35]:
# Check if the assignment is according in the two methods

if_time_scn_ch[0][0] == if_time_ch1_scn_0


array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [13]:
# set up an array that contains the all the interframe delays, one array per scenario        
interframe_delays_scn_0 = np.transpose(np.array([if_time_ch1_scn_0,
                                                 if_time_ch2_scn_0,
                                                 if_time_ch3_scn_0,
                                                 if_time_ch4_scn_0])) # Scenario 0
interframe_delays_scn_1 = np.transpose(np.array([if_time_ch1_scn_1,
                                                 if_time_ch2_scn_1,
                                                 if_time_ch3_scn_1,
                                                 if_time_ch4_scn_1])) # Scenario 1
interframe_delays_scn_2 = np.transpose(np.array([if_time_ch1_scn_2,
                                                 if_time_ch2_scn_2,
                                                 if_time_ch3_scn_2,
                                                 if_time_ch4_scn_2])) # Scenario 2
interframe_delays_scn_3 = np.transpose(np.array([if_time_ch1_scn_3,
                                                 if_time_ch2_scn_3,
                                                 if_time_ch3_scn_3,
                                                 if_time_ch4_scn_3])) # Scenario 3
interframe_delays_scn_4 = np.transpose(np.array([if_time_ch1_scn_4,
                                                 if_time_ch2_scn_4,
                                                 if_time_ch3_scn_4,
                                                 if_time_ch4_scn_4]))# Scenario 4
interframe_delays_scn_5 = np.transpose(np.array([if_time_ch1_scn_5,
                                                 if_time_ch2_scn_5,
                                                 if_time_ch3_scn_5,
                                                 if_time_ch4_scn_5])) # Scenario 5
interframe_delays_scn_6 = np.transpose(np.array([if_time_ch1_scn_6,
                                                 if_time_ch2_scn_6,
                                                 if_time_ch3_scn_6,
                                                 if_time_ch4_scn_6])) # Scenario 6
interframe_delays_scn_7 = np.transpose(np.array([if_time_ch1_scn_7,
                                                 if_time_ch2_scn_7,
                                                 if_time_ch3_scn_7,
                                                 if_time_ch4_scn_7])) # Scenario 7
interframe_delays_scn_8 = np.transpose(np.array([if_time_ch1_scn_8,
                                                 if_time_ch2_scn_8,
                                                 if_time_ch3_scn_8,
                                                 if_time_ch4_scn_8])) # Scenario 8
interframe_delays_scn_9 = np.transpose(np.array([if_time_ch1_scn_9,
                                                 if_time_ch2_scn_9,
                                                 if_time_ch3_scn_9,
                                                 if_time_ch4_scn_9])) # Scenario 9                                  

In [43]:
# Do the same automation for the interframe_delays in a list
interframe_delays_scn = [[] for i in range(N_SCN)]
for scenario in range(N_SCN):
    interframe_delays_scn[scenario] = np.transpose(np.array([if_time_scn_ch[scenario][channel] for channel in range(N_CHAN)]))

In [44]:
# Check that the assignment is according with a random choice
interframe_delays_scn[4] == interframe_delays_scn_4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       ..., 
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [49]:
# Be sure all the interframe delays have the same shape
print(type(interframe_delays_scn_0))
print("Shape interframe delays for scenario 0: {}".format(interframe_delays_scn_0.shape))
print("Shape interframe delays for scenario 1: {}".format(interframe_delays_scn_1.shape))
print("Shape interframe delays for scenario 2: {}".format(interframe_delays_scn_2.shape))
print("Shape interframe delays for scenario 3: {}".format(interframe_delays_scn_3.shape))
print("Shape interframe delays for scenario 4: {}".format(interframe_delays_scn_4.shape))
print("Shape interframe delays for scenario 5: {}".format(interframe_delays_scn_5.shape))
print("Shape interframe delays for scenario 6: {}".format(interframe_delays_scn_6.shape))
print("Shape interframe delays for scenario 7: {}".format(interframe_delays_scn_7.shape))
print("Shape interframe delays for scenario 8: {}".format(interframe_delays_scn_8.shape))
print("Shape interframe delays for scenario 9: {}".format(interframe_delays_scn_9.shape))

<class 'numpy.ndarray'>
Shape interframe delays for scenario 0: (1110, 4)
Shape interframe delays for scenario 1: (570, 4)
Shape interframe delays for scenario 2: (1110, 4)
Shape interframe delays for scenario 3: (570, 4)
Shape interframe delays for scenario 4: (2230, 4)
Shape interframe delays for scenario 5: (4480, 4)
Shape interframe delays for scenario 6: (10160, 4)
Shape interframe delays for scenario 7: (1120, 4)
Shape interframe delays for scenario 8: (2130, 4)
Shape interframe delays for scenario 9: (3920, 4)


In [53]:
# Be sure all the interframe delays have the same shape
print(type(interframe_delays_scn))
print(type(interframe_delays_scn[0]))
for scenario in range(N_SCN):
    print("Shape Interframe delays for scenario {}: {}".format(scenario, interframe_delays_scn[scenario].shape))

<class 'list'>
<class 'numpy.ndarray'>
Shape Interframe delays for scenario 0: (1110, 4)
Shape Interframe delays for scenario 1: (570, 4)
Shape Interframe delays for scenario 2: (1110, 4)
Shape Interframe delays for scenario 3: (570, 4)
Shape Interframe delays for scenario 4: (2230, 4)
Shape Interframe delays for scenario 5: (4480, 4)
Shape Interframe delays for scenario 6: (10160, 4)
Shape Interframe delays for scenario 7: (1120, 4)
Shape Interframe delays for scenario 8: (2130, 4)
Shape Interframe delays for scenario 9: (3920, 4)


In [10]:
# Packet rate                                                                   
packet_rate_scn_0 = sp.fromfile(open("packet_rate_scn_0.dat"), dtype=sp.float32) # Scenario 0  
packet_rate_scn_1 = sp.fromfile(open("packet_rate_scn_1.dat"), dtype=sp.float32) # Scenario 1  
packet_rate_scn_2 = sp.fromfile(open("packet_rate_scn_2.dat"), dtype=sp.float32) # Scenario 2  
packet_rate_scn_3 = sp.fromfile(open("packet_rate_scn_3.dat"), dtype=sp.float32) # Scenario 3  
packet_rate_scn_4 = sp.fromfile(open("packet_rate_scn_4.dat"), dtype=sp.float32) # Scenario 4  
packet_rate_scn_5 = sp.fromfile(open("packet_rate_scn_5.dat"), dtype=sp.float32) # Scenario 5  
packet_rate_scn_6 = sp.fromfile(open("packet_rate_scn_6.dat"), dtype=sp.float32) # Scenario 6  
packet_rate_scn_7 = sp.fromfile(open("packet_rate_scn_7.dat"), dtype=sp.float32) # Scenario 7  
packet_rate_scn_8 = sp.fromfile(open("packet_rate_scn_8.dat"), dtype=sp.float32) # Scenario 8  
packet_rate_scn_9 = sp.fromfile(open("packet_rate_scn_9.dat"), dtype=sp.float32) # Scenario 9  
                                                                                
# Variance inter frame delay                                                    
variance_scn_0 = sp.fromfile(open("variance_scn_0.dat"), dtype=sp.float32)       # Scenario 0                
variance_scn_1 = sp.fromfile(open("variance_scn_1.dat"), dtype=sp.float32)       # Scenario 1                
variance_scn_2 = sp.fromfile(open("variance_scn_2.dat"), dtype=sp.float32)       # Scenario 2                
variance_scn_3 = sp.fromfile(open("variance_scn_3.dat"), dtype=sp.float32)       # Scenario 3                
variance_scn_4 = sp.fromfile(open("variance_scn_4.dat"), dtype=sp.float32)       # Scenario 4                
variance_scn_5 = sp.fromfile(open("variance_scn_5.dat"), dtype=sp.float32)       # Scenario 5                
variance_scn_6 = sp.fromfile(open("variance_scn_6.dat"), dtype=sp.float32)       # Scenario 6                
variance_scn_7 = sp.fromfile(open("variance_scn_7.dat"), dtype=sp.float32)       # Scenario 7                
variance_scn_8 = sp.fromfile(open("variance_scn_8.dat"), dtype=sp.float32)       # Scenario 8                
variance_scn_9 = sp.fromfile(open("variance_scn_9.dat"), dtype=sp.float32)       # Scenario 9   

In [55]:
# Create iterables for packet rate and variance
packet_rate_scn = [[] for scenario in range(N_SCN)]
variance_scn = [[] for scenario in range(N_SCN)]

for scenario in range(N_SCN):
    packet_rate_scn[scenario] = sp.fromfile(open("packet_rate_scn_{}.dat".format(scenario)),
                                                dtype=sp.float32)
    variance_scn[scenario] = sp.fromfile(open("variance_scn_{}.dat".format(scenario)),
                                             dtype=sp.float32)

In [57]:
# Check validity of iterable again

print(packet_rate_scn[4] == packet_rate_scn_4)
print(variance_scn[4] == variance_scn_4)

[ True  True  True ...,  True  True  True]
[ True  True  True ...,  True  True  True]


In [58]:
# Generate a channel ocupation feature
channel_ocupation_scn = [[] for scenario in range(N_SCN)]
for scenario in range(N_SCN):
    channel_ocupation_scn[scenario] = interframe_delays_scn[scenario] > 0

In [73]:
# create lists to describe dataset
features_names = ['Interframe delay ch 1', 'Interframe delay ch 2', 'Interframe delay ch 3', 'Interframe delay ch 4', 'Packet Rate', 'Variance IFD']
target_names = ["Scenario {}".format(i) for i in range(N_SCN)]
target = np.array([scenario for scenario in range(N_SCN)])
data = np.array(list(zip(if_time_scn_ch, packet_rate_scn, variance_scn, channel_ocupation_scn)))

In [77]:
# generate a dict to use as dataset
ml_dataset = {}
ml_dataset['feature_names'] = features_names
ml_dataset['target_names'] = target_names
ml_dataset['target'] = target
ml_dataset['data'] = data

In [66]:
# Start MLearning with train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(ml_dataset['data'], ml_dataset['target'], random_state=0)

In [67]:
data

array([[ [array([-0.35840458, -0.35840458, -0.35840458, ..., -1.        ,
       -1.        , -1.        ], dtype=float32), array([-1., -1., -1., ..., -1., -1., -1.], dtype=float32), array([-1., -1., -1., ..., -1., -1., -1.], dtype=float32), array([ 5.00486422,  5.00344181,  5.00303555, ...,  5.00196695,
        5.00144863,  5.00148869], dtype=float32)],
        array([ 2122.93481445,   992.93334961,   648.00933838, ...,   190.10122681,
         190.11975098,   190.11975098], dtype=float32),
        array([ 0.12846743,  0.12848413,  0.12850057, ...,  0.12861934,
        0.12861699,  0.12862049], dtype=float32),
        array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       ..., 
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]], dtype=bool)],
       [ [array([-0.35840458, -0.35840458, -0.35840458, -0.35840458, -0.35840455,
       -0.35840458, -0.35840458, -0.35840

In [71]:
print("Shape of data: {}".format(ml_dataset['data'].shape))

Shape of data: (10, 4)
First five columnds of data:
[[ [array([-0.35840458, -0.35840458, -0.35840458, ..., -1.        ,
       -1.        , -1.        ], dtype=float32), array([-1., -1., -1., ..., -1., -1., -1.], dtype=float32), array([-1., -1., -1., ..., -1., -1., -1.], dtype=float32), array([ 5.00486422,  5.00344181,  5.00303555, ...,  5.00196695,
        5.00144863,  5.00148869], dtype=float32)]
  array([ 2122.93481445,   992.93334961,   648.00933838, ...,   190.10122681,
         190.11975098,   190.11975098], dtype=float32)
  array([ 0.12846743,  0.12848413,  0.12850057, ...,  0.12861934,
        0.12861699,  0.12862049], dtype=float32)
  array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       ..., 
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]], dtype=bool)]
 [ [array([-0.35840458, -0.35840458, -0.35840458, -0.35840458, -0.35840455,
       -0.35840458, -0.

In [78]:
print("Shape of target: {}".format(ml_dataset['target'].shape))

Shape of target: (10,)
